# Basis Object Usage
This notebook documents the ways of creating and manipulating bases, providing code that can be copied. For more detailed documentation, see the basis class itself. 

In [41]:
from pygsti import Basis
Basis('pp', 2)

Pauli-Product Basis : I, X, Y, Z

In [42]:
Basis('std', [2, 1])

Matrix-unit Basis : (0,0), (0,1), (1,0), (1,1), (2,2)

In [43]:
Basis([('std', 2), ('gm', 2)])

std,gm Basis : M(std,gm)[0,0], M(std,gm)[0,1], M(std,gm)[0,2], M(std,gm)[0,3], M(std,gm)[1,0], M(std,gm)[1,1], M(std,gm)[1,2], M(std,gm)[1,3]

In [44]:
std = Basis('std', 2)
gm  = Basis('gm', 2)

composite = Basis([std, gm])
composite

std,gm Basis : M(std,gm)[0,0], M(std,gm)[0,1], M(std,gm)[0,2], M(std,gm)[0,3], M(std,gm)[1,0], M(std,gm)[1,1], M(std,gm)[1,2], M(std,gm)[1,3]

In [45]:
comp = Basis(matrices=[std, gm], name='comp', longname='CustomComposite')
comp

CustomComposite Basis : M(std,gm)[0,0], M(std,gm)[0,1], M(std,gm)[0,2], M(std,gm)[0,3], M(std,gm)[1,0], M(std,gm)[1,1], M(std,gm)[1,2], M(std,gm)[1,3]

In [46]:
comp.labels = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
comp

CustomComposite Basis : A, B, C, D, E, F, G, H

In [47]:
comp = Basis(matrices=[std, gm], name='comp', longname='CustomComposite', labels=[
        'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'
    ])
comp

CustomComposite Basis : A, B, C, D, E, F, G, H

In [48]:
import numpy as np
alt_standard = Basis(matrices=[
        np.array([[1, 0],
                  [0, 0]]),
        np.array([[0, 1],
                  [0, 0]]),
        np.array([[0, 0],
                  [1, 0]]),
        np.array([[0, 0],
                  [0, 1]])],
                     name='std',
                     longname='Standard'
                    )
alt_standard

Standard Basis : (0,0), (0,1), (1,0), (1,1)

### Basis Changing:

In [49]:
mx = np.array([
        [1, 0, 0, 1],
        [0, 1, 2, 0],
        [0, 2, 1, 0],
        [1, 0, 0, 1]
    ])
mx

array([[1, 0, 0, 1],
       [0, 1, 2, 0],
       [0, 2, 1, 0],
       [1, 0, 0, 1]])

In [50]:
from pygsti import change_basis
change_basis(mx, 'std', 'gm') # shortname lookup

array([[ 2.,  0.,  0.,  0.],
       [ 0.,  3.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [51]:
change_basis(mx, std, gm) # object

array([[ 2.,  0.,  0.,  0.],
       [ 0.,  3.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [52]:
change_basis(mx, std, 'gm') # combination

array([[ 2.,  0.,  0.,  0.],
       [ 0.,  3.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.]])

### Automatic matrix resizing during basis change:

In [53]:
mxInStdBasis = np.array([[1,0,0,2],
                         [0,0,0,0],
                         [0,0,0,0],
                         [3,0,0,4]],'d')

# Reduce to a matrix operating on a density matrix space with 2 1x1 blocks (hence [1,1])
begin = Basis('std', [1,1])
end   = Basis('std', 2)
        
mxInReducedBasis = change_basis(mxInStdBasis, begin, end)
mxInReducedBasis

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [54]:
original = change_basis(mxInReducedBasis, end, begin)
original

array([[ 1.+0.j,  0.+0.j,  0.+0.j,  2.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 3.+0.j,  0.+0.j,  0.+0.j,  4.+0.j]])