In [7]:
import pygsti
from pygsti.objects import Circuit
from pygsti.baseobjs import Label
from pygsti.objects import ProcessorSpec
import numpy as np

In [8]:
from pygsti.extras import rb

In [9]:
cl = rb.group.construct_1Q_Clifford_group()

In [10]:
#pygsti.tools.get_symplectic_matrix(0,1)

In [11]:
d = pygsti.tools.internalgates.std_unitaries

In [20]:
for l in range(24):
    assert(np.allclose(pygsti.unitary_to_pauligate(d['C'+str(l)]),cl.get_matrix(l)))
    print(l)
    s, p = pygsti.symplectic.unitary_to_symplectic(d['C'+str(l)])
    print(s)
    print(p)

0
[[1 0]
 [0 1]]
[0 0]
1
[[1 1]
 [1 0]]
[1 0]
2
[[0 1]
 [1 1]]
[0 1]
3
[[1 0]
 [0 1]]
[0 2]
4
[[1 1]
 [1 0]]
[1 2]
5
[[0 1]
 [1 1]]
[0 3]
6
[[1 0]
 [0 1]]
[2 2]
7
[[1 1]
 [1 0]]
[3 2]
8
[[0 1]
 [1 1]]
[2 3]
9
[[1 0]
 [0 1]]
[2 0]
10
[[1 1]
 [1 0]]
[3 0]
11
[[0 1]
 [1 1]]
[2 1]
12
[[0 1]
 [1 0]]
[0 0]
13
[[1 1]
 [0 1]]
[0 1]
14
[[1 0]
 [1 1]]
[1 0]
15
[[0 1]
 [1 0]]
[0 2]
16
[[1 1]
 [0 1]]
[0 3]
17
[[1 0]
 [1 1]]
[1 2]
18
[[0 1]
 [1 0]]
[2 2]
19
[[1 1]
 [0 1]]
[2 3]
20
[[1 0]
 [1 1]]
[3 2]
21
[[0 1]
 [1 0]]
[2 0]
22
[[1 1]
 [0 1]]
[2 1]
23
[[1 0]
 [1 1]]
[3 0]


In [12]:
for l in cl.label_indices:
    leaveloop = False
    for unitary1 in d.values():
        for unitary2 in d.values():
            for unitary3 in d.values(): 
                u = np.dot(unitary1,unitary2)
                u = np.dot(unitary3,u)
                if np.allclose(pygsti.unitary_to_pauligate(u),cl.get_matrix(l)):
                    print(l,u,)
                    leaveloop = True
                    break
            if leaveloop:
                break
        if leaveloop:
            break

Gc0 [[ 1.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j]]
Gc1 [[ 0.70710678+0.j          0.00000000-0.70710678j]
 [ 0.70710678+0.j          0.00000000+0.70710678j]]
Gc2 [[ 0.70710678+0.j          0.70710678+0.j        ]
 [ 0.00000000+0.70710678j  0.00000000-0.70710678j]]
Gc3 [[ 0.+0.j  1.+0.j]
 [ 1.+0.j  0.+0.j]]
Gc4 [[-0.70710678+0.j          0.00000000-0.70710678j]
 [ 0.70710678+0.j          0.00000000-0.70710678j]]
Gc5 [[ 0.70710678+0.j          0.70710678+0.j        ]
 [ 0.00000000-0.70710678j  0.00000000+0.70710678j]]
Gc6 [[ 0.+0.j  0.-1.j]
 [ 0.+1.j  0.+0.j]]
Gc7 [[ 0.00000000+0.70710678j  0.70710678+0.j        ]
 [ 0.00000000-0.70710678j  0.70710678+0.j        ]]
Gc8 [[ 0.00000000+0.70710678j  0.00000000-0.70710678j]
 [ 0.70710678+0.j          0.70710678+0.j        ]]
Gc9 [[ 1.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]]
Gc10 [[ 0.70710678+0.j          0.00000000+0.70710678j]
 [ 0.70710678+0.j          0.00000000-0.70710678j]]
Gc11 [[ 0.70710678+0.j         -0.70710678+0.j        ]
 [ 0.00000000+0.707106

In [ ]:
cl.label_indices

In [ ]:
a = orderedqubits.copy()

In [ ]:
del a[0]

In [ ]:
print(orderedqubits)

In [ ]:
orderedqubits = [1,[2,3],4]
[q for sublist in orderedqubits for q in sublist]

In [ ]:
n = 7
gate_names=['Gi','Gh','Gp','Ghp','Gcphase']
qubit_labels=['Q'+str(i) for i in range(0,7)]
print(qubit_labels)
availability = {'Gcphase':[('Q'+str(i),'Q'+str(i+1)) for i in range(0,n-2)]+[('Q'+str(n-2),'Q'+str(0)),]+[('Q'+str(i),'Q'+str(n-1)) for i in range(0,n-1)]}
ps = ProcessorSpec(n,gate_names=gate_names,availability=availability, qubit_labels=qubit_labels,  construct_clifford_compilations = {'paulieq' : ('1Qcliffords','allcnots'), 
                'absolute': ('paulis',)}, verbosity=0)

In [ ]:
s, p = pygsti.symplectic.random_clifford(n)

In [ ]:
c = pygsti.algorithms.compile_clifford(s,p)

In [ ]:
#print(c)

In [ ]:
c = pygsti.algorithms.compile_clifford(s,p,pspec=ps)

In [ ]:
print(c)