In [1]:
import pygsti
from pygsti.objects import Circuit
from pygsti.baseobjs import Label
from pygsti.objects import ProcessorSpec
import pickle
import numpy as np
from pygsti.extras import rb

In [59]:
A = np.random.randint(10,size=(4,4))
print(A)
i = 1
k = 3
A[[i, k],:] = A[[k, i],:]
print('')
print(A)

[[6 5 5 0]
 [0 7 2 8]
 [1 2 6 5]
 [6 2 0 7]]

[[6 5 5 0]
 [6 2 0 7]
 [1 2 6 5]
 [0 7 2 8]]


In [2]:
from scipy import sparse
import time

In [48]:
C = sparse.csr_matrix((1,(0,0)), [(10,10),])
print(C)
A = np.ones((100,100),int)

ValueError: not enough values to unpack (expected 2, got 1)

In [ ]:
C 

In [12]:
C = sparse.csc_matrix(np.array([[1,1], [0,2]]))

In [14]:
C

<2x2 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Column format>

In [ ]:
a = [1,2,3,4]

In [ ]:
a[3:]

In [ ]:
sectors = [[Label('Gcphase',('Q'+str(i),'Q'+str(i+1))),] for i in [3,]]

In [ ]:
#sectors 

In [ ]:
c = ps.compilations['absolute'].get_compilation_of(Label('X','Q2'))

In [ ]:
print(c)

In [ ]:
# Insert layer is failing?
# Appending the circuits at the start and end is failing?
c, o = rb.sample.mirror_rb_circuit(ps, 6, subsetQs=['Q3','Q4'], sampler='sectors', samplerargs=[sectors,])

In [ ]:
print(c)

In [ ]:
print(c.depth())
print(6*4)

In [ ]:
s, p = pygsti.symplectic.random_clifford(n)
c = pygsti.algorithms.compilesymplectic.compile_symplectic(s, pspec=None, iterations=20, algorithms='RBGGE', costfunction='2QGC', paulirandomize=False, aargs=None)

In [ ]:
print(c)

In [ ]:
comp = ps.compilations['paulieq']

In [ ]:
comp.get_compilation_of(Label('P','Q0'),allowed_filter=None)

In [ ]:
c.change_gate_library(ps.compilations['paulieq'],allow_unchanged_gates=False)

In [ ]:
print(c)

In [ ]:
{i:i+1 for i in range(10) }

In [ ]:
com = ps.compilations['paulieq']

In [ ]:
isinstance(com,CompilationLibrary)

In [ ]:
subset = set(['Q'+str(i) for i in range(0,6)])
print(subset)

In [ ]:
circuit = com.get_compilation_of(Label('CNOT',('Q1','Q4')),allowed_filter=subset)
print(circuit)

In [ ]:
com.add_compilation_of(Label('CNOT',('Q1','Q4')),allowed_filter=subset)

In [ ]:
from pygsti.objects import CompilationLibrary
isinstance(com,CompilationLibrary)

In [ ]:
print(list(com.keys()))

In [ ]:
fs = {}

In [ ]:
fs['a',None] = 1

In [ ]:
fs.keys()

In [ ]:
d = O {'a':1,'b':2}

In [ ]:
fs = frozenset(d.items())

In [ ]:
fs = dict(fs)

In [ ]:
isinstance(fs, dict)

In [ ]:
gs = ps.models['clifford']

In [ ]:
gs.stateSpaceLabels.labels

In [ ]:
d = {'a':0}
d.get('a',1)

In [ ]:
#ps.models['clifford'].gates

In [ ]:
ps.compilations['paulieq'].connectivity

In [ ]:
ps.compilations

In [ ]:
ps = ProcessorSpec(1,['Gi','Gh','Gp'],qubit_labels=['Q1',], verbosity=0)

In [ ]:
ps.fafs

In [ ]:
ps.oneQgate_algebra

In [ ]:
ps.oneQgate_inversions

In [ ]:
gs = ps.models['clifford']

In [ ]:
gs.

In [ ]:
import itertools

In [ ]:
a = itertools.permutations(['a','b','c'], 2)

In [ ]:
list(a)

In [ ]:
ps.compilations['paulieq']

In [ ]:
ps.qubitgraph.subgraph?

In [ ]:
with open('test19.pkl','wb') as f:
    pickle.dump(ps,f)

In [ ]:
ps.compilations

In [ ]:
ps = ProcessorSpec(4,['Gi','Gh','Gp','Gcnot'],qubit_labels=['Q0','Q1','Q2','Q3'])

In [ ]:
# Circuit initialization tests
gatestring=[Label('Gh','Q1'),Label('Gcnot',('Q1','Q2'))]
line_items =[[Label('Gh','Q0')],[Label('Gh','Q1')],[Label('Gh','Q2')],[Label('Gh','Q3')]]

# Check can initialize with gatestring
c = pygsti.obj.Circuit(gatestring=gatestring,line_labels=['Q0','Q1','Q2','Q3'],identity='Gi')
s = c.__str__()
size = c.size()
depth = c.depth()
twoQgc = c.twoqubit_gatecount()
assert(depth == 2)
assert(size == 3)
assert(twoQgc == 1)

# Check can initialize with line_items
c = pygsti.obj.Circuit(line_items=line_items,line_labels=['Q0','Q1','Q2','Q3'],identity='Gi')
s = c.__str__()
depth = c.depth()
size = c.size()
twoQgc = c.twoqubit_gatecount()
assert(depth == 1)
assert(size == 4)
assert(twoQgc == 0)

# Check can't give line_items and gatestring.
try:
    c = pygsti.obj.Circuit(line_items=line_items,gatestring=gatestring)
    failed = False
except:
    failed = True
assert(failed)



In [ ]:
c2 = c.copy()

In [ ]:
c.replace_gatename('Gh','Gp')
print(c)

In [ ]:
c2

In [ ]:
# Check we can create an empty circuit
c = pygsti.obj.Circuit(num_lines=10)
depth = c.depth()
size = c.size()
twoQgc = c.twoqubit_gatecount()
assert(depth == 0)
assert(size == 0)
assert(twoQgc == 0)

In [ ]:
gatestring= [Label('Gh','Q1'),Label('Gh','Q2'),Label('Gh','Q3')]
c = pygsti.obj.Circuit(gatestring=gatestring,num_lines=3,identity='Gi')

In [ ]:
c

In [ ]:
c.line_items

In [ ]:
c.line_labels

In [ ]:
for q in Label('Gh','Q1').qubits:
    assert(q in c.line_labels)

In [ ]:
ProcessorSpec?

In [ ]:
ps.