In [1]:
import stim
import pygsti
from pygsti.extras.idletomography.idtcore import correlation_jac_alt, build_class_jacobian
from pygsti.extras.idletomography.pauliobjs import NQPauliState
import numpy as np

In [2]:
cor_jac , pairs, _=  correlation_jac_alt(1)

In [3]:
cor_jac

array([[ 0.,  0.,  0.],
       [ 2.,  0.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  0.],
       [-2.,  0.,  0.],
       [ 0., -2.,  0.],
       [ 2.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  2.],
       [-2.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0., -2.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  2.],
       [ 0.,  0.,  0.],
       [ 0., -2.,  0.],
       [ 0.,  0., -2.],
       [ 0.,  0.,  0.]])

In [4]:
pairs

[('+X', '+X'),
 ('+X', '+Y'),
 ('+X', '+Z'),
 ('-X', '+X'),
 ('-X', '+Y'),
 ('-X', '+Z'),
 ('+Y', '+X'),
 ('+Y', '+Y'),
 ('+Y', '+Z'),
 ('-Y', '+X'),
 ('-Y', '+Y'),
 ('-Y', '+Z'),
 ('+Z', '+X'),
 ('+Z', '+Y'),
 ('+Z', '+Z'),
 ('-Z', '+X'),
 ('-Z', '+Y'),
 ('-Z', '+Z')]

In [5]:
build_class_jacobian('C',1)

4


{(('+X', '+Y'), ('X', 'Y')): 2.0,
 (('-X', '+Y'), ('X', 'Y')): -2.0,
 (('+X', '+Z'), ('X', 'Z')): 2.0,
 (('-X', '+Z'), ('X', 'Z')): -2.0,
 (('+X', '+Y'), ('Y', 'X')): 2.0,
 (('-X', '+Y'), ('Y', 'X')): -2.0,
 (('+X', '+Z'), ('Z', 'X')): 2.0,
 (('-X', '+Z'), ('Z', 'X')): -2.0,
 (('+Y', '+X'), ('X', 'Y')): 2.0,
 (('-Y', '+X'), ('X', 'Y')): -2.0,
 (('+Y', '+X'), ('Y', 'X')): 2.0,
 (('-Y', '+X'), ('Y', 'X')): -2.0,
 (('+Y', '+Z'), ('Y', 'Z')): 2.0,
 (('-Y', '+Z'), ('Y', 'Z')): -2.0,
 (('+Y', '+Z'), ('Z', 'Y')): 2.0,
 (('-Y', '+Z'), ('Z', 'Y')): -2.0,
 (('+Z', '+X'), ('X', 'Z')): 2.0,
 (('-Z', '+X'), ('X', 'Z')): -2.0,
 (('+Z', '+Y'), ('Y', 'Z')): 2.0,
 (('-Z', '+Y'), ('Y', 'Z')): -2.0,
 (('+Z', '+X'), ('Z', 'X')): 2.0,
 (('-Z', '+X'), ('Z', 'X')): -2.0,
 (('+Z', '+Y'), ('Z', 'Y')): 2.0,
 (('-Z', '+Y'), ('Z', 'Y')): -2.0}

In [6]:
cor_jac_orig = build_class_jacobian('C', 1)
#refactor this to match output of new code
cor_jac_orig_refactored_dict = {}
for pair in pairs:
    cor_jac_orig_refactored_dict[pair] = np.zeros((1,3))
    for (key, val) in cor_jac_orig.items():
        if key[0] == pair:
            if key[1] ==('X', 'Y'):
                cor_jac_orig_refactored_dict[pair] += np.array([val, 0, 0])
            if key[1] ==('X', 'Z'):
                cor_jac_orig_refactored_dict[pair] += np.array([0, val, 0])
            if key[1] == ('Y', 'Z'):
                cor_jac_orig_refactored_dict[pair] += np.array([0, 0, val])

cor_jac_orig_refactored = np.concatenate([array for array in cor_jac_orig_refactored_dict.values()], axis = 0)
print(cor_jac_orig_refactored_dict)
print(cor_jac_orig_refactored)

4
{('+X', '+X'): array([[0., 0., 0.]]), ('+X', '+Y'): array([[2., 0., 0.]]), ('+X', '+Z'): array([[0., 2., 0.]]), ('-X', '+X'): array([[0., 0., 0.]]), ('-X', '+Y'): array([[-2.,  0.,  0.]]), ('-X', '+Z'): array([[ 0., -2.,  0.]]), ('+Y', '+X'): array([[2., 0., 0.]]), ('+Y', '+Y'): array([[0., 0., 0.]]), ('+Y', '+Z'): array([[0., 0., 2.]]), ('-Y', '+X'): array([[-2.,  0.,  0.]]), ('-Y', '+Y'): array([[0., 0., 0.]]), ('-Y', '+Z'): array([[ 0.,  0., -2.]]), ('+Z', '+X'): array([[0., 2., 0.]]), ('+Z', '+Y'): array([[0., 0., 2.]]), ('+Z', '+Z'): array([[0., 0., 0.]]), ('-Z', '+X'): array([[ 0., -2.,  0.]]), ('-Z', '+Y'): array([[ 0.,  0., -2.]]), ('-Z', '+Z'): array([[0., 0., 0.]])}
[[ 0.  0.  0.]
 [ 2.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  0.]
 [-2.  0.  0.]
 [ 0. -2.  0.]
 [ 2.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  2.]
 [-2.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -2.]
 [ 0.  2.  0.]
 [ 0.  0.  2.]
 [ 0.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0. -2.]
 [ 0.  0.  0.]]


In [7]:
j=0
for i in range(len(pairs)):
    #only print the ones where the prep and meas are the same.
    #if pairs[i][0][-1] != pairs[i][1][-1]:
    #    continue
    print(f'{pairs[i]}  {cor_jac[i,:]}  {cor_jac_orig_refactored[j, :]}')
    j+=1

('+X', '+X')  [0. 0. 0.]  [0. 0. 0.]
('+X', '+Y')  [2. 0. 0.]  [2. 0. 0.]
('+X', '+Z')  [0. 2. 0.]  [0. 2. 0.]
('-X', '+X')  [0. 0. 0.]  [0. 0. 0.]
('-X', '+Y')  [-2.  0.  0.]  [-2.  0.  0.]
('-X', '+Z')  [ 0. -2.  0.]  [ 0. -2.  0.]
('+Y', '+X')  [2. 0. 0.]  [2. 0. 0.]
('+Y', '+Y')  [0. 0. 0.]  [0. 0. 0.]
('+Y', '+Z')  [0. 0. 2.]  [0. 0. 2.]
('-Y', '+X')  [-2.  0.  0.]  [-2.  0.  0.]
('-Y', '+Y')  [0. 0. 0.]  [0. 0. 0.]
('-Y', '+Z')  [ 0.  0. -2.]  [ 0.  0. -2.]
('+Z', '+X')  [0. 2. 0.]  [0. 2. 0.]
('+Z', '+Y')  [0. 0. 2.]  [0. 0. 2.]
('+Z', '+Z')  [0. 0. 0.]  [0. 0. 0.]
('-Z', '+X')  [ 0. -2.  0.]  [ 0. -2.  0.]
('-Z', '+Y')  [ 0.  0. -2.]  [ 0.  0. -2.]
('-Z', '+Z')  [0. 0. 0.]  [0. 0. 0.]


Check the 2-qubit case

In [8]:
cor_jac_2 , pairs_2, cor_pauli_idxs_2=  correlation_jac_alt(2)

In [11]:
cor_pauli_idxs_2

array([(stim.PauliString("+_X"), stim.PauliString("+_Y")),
       (stim.PauliString("+_X"), stim.PauliString("+_Z")),
       (stim.PauliString("+_X"), stim.PauliString("+X_")),
       (stim.PauliString("+_X"), stim.PauliString("+XX")),
       (stim.PauliString("+_X"), stim.PauliString("+XY")),
       (stim.PauliString("+_X"), stim.PauliString("+XZ")),
       (stim.PauliString("+_X"), stim.PauliString("+Y_")),
       (stim.PauliString("+_X"), stim.PauliString("+YX")),
       (stim.PauliString("+_X"), stim.PauliString("+YY")),
       (stim.PauliString("+_X"), stim.PauliString("+YZ")),
       (stim.PauliString("+_X"), stim.PauliString("+Z_")),
       (stim.PauliString("+_X"), stim.PauliString("+ZX")),
       (stim.PauliString("+_X"), stim.PauliString("+ZY")),
       (stim.PauliString("+_X"), stim.PauliString("+ZZ")),
       (stim.PauliString("+_Y"), stim.PauliString("+_Z")),
       (stim.PauliString("+_Y"), stim.PauliString("+X_")),
       (stim.PauliString("+_Y"), stim.PauliString("+XX")

In [9]:
cor_jac_2.shape

(972, 105)

In [47]:
cor_jac_orig_2 = build_class_jacobian('C', 2)

#refactor this to match output of new code
cor_jac_orig_refactored_dict_2 = {}
seen_pairs = []
for pair in pairs_2:
    cor_jac_orig_refactored_dict_2[pair] = np.zeros((1,len(cor_pauli_idxs_2)))
    for (key, val) in cor_jac_orig_2.items():
        if key[0] == pair:
            seen_pairs.append(pair)
            #get the index in cor_pauli_idxs_2 for key[1]
            try:
                cor_pauli_idx = list(cor_pauli_idxs_2).index((stim.PauliString(key[1][0]), stim.PauliString(key[1][1])))
            except ValueError:
                
                continue
            temp_array = np.zeros((1,len(cor_pauli_idxs_2)))
            temp_array[0, cor_pauli_idx] = val
            cor_jac_orig_refactored_dict_2[pair] += temp_array
            
cor_jac_orig_refactored_2 = np.concatenate([array for array in cor_jac_orig_refactored_dict_2.values()], axis = 0)
print(cor_jac_orig_refactored_dict_2)
print(cor_jac_orig_refactored_2)

16
{('+X+X', '+X+X'): array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]]), ('+X+X', '+X-X'): array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]]), ('

In [15]:
(stim.PauliString(key[1][0]), stim.PauliString(key[1][1]))

(stim.PauliString("+_X"), stim.PauliString("+_Y"))

In [20]:
cor_jac_orig_2

{(('+X+X', '+X+Y'), ('IX', 'IY')): 2.0,
 (('+X-X', '+X+Y'), ('IX', 'IY')): -2.0,
 (('-X+X', '+X+Y'), ('IX', 'IY')): -2.0,
 (('-X-X', '+X+Y'), ('IX', 'IY')): 2.0,
 (('+X+X', '+X+Z'), ('IX', 'IZ')): 2.0,
 (('+X-X', '+X+Z'), ('IX', 'IZ')): -2.0,
 (('-X+X', '+X+Z'), ('IX', 'IZ')): -2.0,
 (('-X-X', '+X+Z'), ('IX', 'IZ')): 2.0,
 (('+X+X', '+X+Y'), ('IY', 'IX')): 2.0,
 (('+X-X', '+X+Y'), ('IY', 'IX')): -2.0,
 (('-X+X', '+X+Y'), ('IY', 'IX')): -2.0,
 (('-X-X', '+X+Y'), ('IY', 'IX')): 2.0,
 (('+X+X', '+Z+Z'), ('IY', 'YI')): 4.0,
 (('+X-X', '+Z+Z'), ('IY', 'YI')): -4.0,
 (('-X+X', '+Z+Z'), ('IY', 'YI')): -4.0,
 (('-X-X', '+Z+Z'), ('IY', 'YI')): 4.0,
 (('+X+X', '+Y+Z'), ('IY', 'ZI')): -4.0,
 (('+X-X', '+Y+Z'), ('IY', 'ZI')): 4.0,
 (('-X+X', '+Y+Z'), ('IY', 'ZI')): 4.0,
 (('-X-X', '+Y+Z'), ('IY', 'ZI')): -4.0,
 (('+X+X', '+X+Z'), ('IZ', 'IX')): 2.0,
 (('+X-X', '+X+Z'), ('IZ', 'IX')): -2.0,
 (('-X+X', '+X+Z'), ('IZ', 'IX')): -2.0,
 (('-X-X', '+X+Z'), ('IZ', 'IX')): 2.0,
 (('+X+X', '+Z+Y'), ('IZ', '

In [33]:

print(list(np.where(np.abs(cor_jac_orig_refactored_2-cor_jac_2)>1e-8)[0]))

[4, 4, 4, 4, 5, 5, 5, 5, 7, 7, 7, 7, 8, 8, 8, 8, 10, 10, 10, 10, 11, 11, 11, 11, 13, 13, 14, 14, 16, 16, 17, 17, 19, 19, 19, 19, 20, 20, 20, 20, 22, 22, 23, 23, 25, 25, 26, 26, 31, 31, 31, 31, 32, 32, 32, 32, 34, 34, 34, 34, 35, 35, 35, 35, 37, 37, 37, 37, 38, 38, 38, 38, 40, 40, 41, 41, 43, 43, 44, 44, 46, 46, 46, 46, 47, 47, 47, 47, 49, 49, 50, 50, 52, 52, 53, 53, 58, 58, 58, 58, 59, 59, 59, 59, 61, 61, 61, 61, 62, 62, 62, 62, 64, 64, 64, 64, 65, 65, 65, 65, 67, 67, 68, 68, 70, 70, 71, 71, 73, 73, 73, 73, 74, 74, 74, 74, 76, 76, 77, 77, 79, 79, 80, 80, 85, 85, 85, 85, 86, 86, 86, 86, 88, 88, 88, 88, 89, 89, 89, 89, 91, 91, 91, 91, 92, 92, 92, 92, 94, 94, 95, 95, 97, 97, 98, 98, 100, 100, 100, 100, 101, 101, 101, 101, 103, 103, 104, 104, 106, 106, 107, 107, 109, 109, 109, 109, 110, 110, 110, 110, 115, 115, 115, 115, 116, 116, 116, 116, 118, 118, 119, 119, 121, 121, 121, 121, 122, 122, 122, 122, 124, 124, 125, 125, 127, 127, 128, 128, 130, 130, 130, 130, 131, 131, 131, 131, 133, 133, 1

In [43]:
cor_jac_orig_refactored_2[4,:]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [37]:
cor_jac_2[4,:]

array([-2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -2.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,
        0.])

In [44]:
pairs_2[4]

('+X+X', '+X-Y')

In [45]:
cor_jac_orig_2

{(('+X+X', '+X+Y'), ('IX', 'IY')): 2.0,
 (('+X-X', '+X+Y'), ('IX', 'IY')): -2.0,
 (('-X+X', '+X+Y'), ('IX', 'IY')): -2.0,
 (('-X-X', '+X+Y'), ('IX', 'IY')): 2.0,
 (('+X+X', '+X+Z'), ('IX', 'IZ')): 2.0,
 (('+X-X', '+X+Z'), ('IX', 'IZ')): -2.0,
 (('-X+X', '+X+Z'), ('IX', 'IZ')): -2.0,
 (('-X-X', '+X+Z'), ('IX', 'IZ')): 2.0,
 (('+X+X', '+X+Y'), ('IY', 'IX')): 2.0,
 (('+X-X', '+X+Y'), ('IY', 'IX')): -2.0,
 (('-X+X', '+X+Y'), ('IY', 'IX')): -2.0,
 (('-X-X', '+X+Y'), ('IY', 'IX')): 2.0,
 (('+X+X', '+Z+Z'), ('IY', 'YI')): 4.0,
 (('+X-X', '+Z+Z'), ('IY', 'YI')): -4.0,
 (('-X+X', '+Z+Z'), ('IY', 'YI')): -4.0,
 (('-X-X', '+Z+Z'), ('IY', 'YI')): 4.0,
 (('+X+X', '+Y+Z'), ('IY', 'ZI')): -4.0,
 (('+X-X', '+Y+Z'), ('IY', 'ZI')): 4.0,
 (('-X+X', '+Y+Z'), ('IY', 'ZI')): 4.0,
 (('-X-X', '+Y+Z'), ('IY', 'ZI')): -4.0,
 (('+X+X', '+X+Z'), ('IZ', 'IX')): 2.0,
 (('+X-X', '+X+Z'), ('IZ', 'IX')): -2.0,
 (('-X+X', '+X+Z'), ('IZ', 'IX')): -2.0,
 (('-X-X', '+X+Z'), ('IZ', 'IX')): 2.0,
 (('+X+X', '+Z+Y'), ('IZ', '

In [ ]:
for 